//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace _5001ProjectNew.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class AbroadTraining
    {
        public string Language { get; set; }
        public string Country { get; set; }
        public string Prerequisites { get; set; }
        public int EmployeeId { get; set; }
        public int InstructorId { get; set; }
        public string CourseName { get; set; }
        public Nullable<System.DateTime> CourseStart { get; set; }
        public Nullable<System.DateTime> CourseEnd { get; set; }
    
        public virtual Course Course { get; set; }
        public virtual Employee Employee { get; set; }
        public virtual Instructor Instructor { get; set; }
    }
}
