//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace _5001ProjectNew.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Employee
    {
        public Employee()
        {
            this.AbroadTrainings = new HashSet<AbroadTraining>();
            this.Reports = new HashSet<Report>();
        }
    
        public int EmployeeId { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string Email { get; set; }
        public string PassingStatus { get; set; }
        public string ProfessionTitle { get; set; }
        public string TrainingCourse { get; set; }
        public string TrainingLocation { get; set; }
        public Nullable<System.DateTime> TrainingStart { get; set; }
        public Nullable<System.DateTime> TrainingEnd { get; set; }
    
        public virtual Contact Contact { get; set; }
        public virtual Course Course { get; set; }
        public virtual ICollection<AbroadTraining> AbroadTrainings { get; set; }
        public virtual ICollection<Report> Reports { get; set; }
    }
}
