//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace _5001ProjectNew.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Instructor
    {
        public Instructor()
        {
            this.Courses = new HashSet<Course>();
            this.Departments = new HashSet<Department>();
            this.AbroadTrainings = new HashSet<AbroadTraining>();
            this.Priviliges = new HashSet<Privilige>();
            this.Reports = new HashSet<Report>();
            this.TrainingSponsors = new HashSet<TrainingSponsor>();
        }
    
        public int InstructorId { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string ProfessionTitle { get; set; }
        public Nullable<System.DateTime> TrainingStart { get; set; }
        public Nullable<System.DateTime> TrainingEnd { get; set; }
        public string TrainingCourse { get; set; }
        public string TrainingLocation { get; set; }
    
        public virtual ICollection<Course> Courses { get; set; }
        public virtual Course Course { get; set; }
        public virtual ICollection<Department> Departments { get; set; }
        public virtual ICollection<AbroadTraining> AbroadTrainings { get; set; }
        public virtual ICollection<Privilige> Priviliges { get; set; }
        public virtual ICollection<Report> Reports { get; set; }
        public virtual ICollection<TrainingSponsor> TrainingSponsors { get; set; }
    }
}
