//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace _5001ProjectNew.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class TrainingTrackingEntities : DbContext
    {
        public TrainingTrackingEntities()
            : base("name=TrainingTrackingEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<Contact> Contacts { get; set; }
        public DbSet<Course> Courses { get; set; }
        public DbSet<Department> Departments { get; set; }
        public DbSet<Employee> Employees { get; set; }
        public DbSet<Instructor> Instructors { get; set; }
        public DbSet<Manager> Managers { get; set; }
        public DbSet<TrainingSponsor> TrainingSponsors { get; set; }
        public DbSet<WebRegister> WebRegisters { get; set; }
        public DbSet<AbroadTraining> AbroadTrainings { get; set; }
        public DbSet<Privilige> Priviliges { get; set; }
        public DbSet<Report> Reports { get; set; }
    }
}
