//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace _5001ProjectNew.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Privilige
    {
        public int ManagerId { get; set; }
        public int InstructorId { get; set; }
        public int DepartmentId { get; set; }
        public string ManagerRanking { get; set; }
        public string Authoraziton { get; set; }
    
        public virtual Department Department { get; set; }
        public virtual Instructor Instructor { get; set; }
        public virtual Manager Manager { get; set; }
    }
}
